### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Raiondesu** [KazanExpress/web-orm#1]
What should be the requirements and use-cases for the project?

**Comment by Raiondesu** [comment]
Based on current README:
* Modular structure - all functional pieces as separate importable modules.
* IndexedDB/WebSQL support with a fallback to localStorage.
* Keep data up-to-date via AJAX or GraphQL data-mapped requests to server.
* Ability to map data entities to request handlers.
* Reasonable minified size (maybe around `20KB`?).
* Transparent interface for dealing with a server-based data (Promises and [Bound](https://github.com/KazanExpress/bound)?)
* SOLID architecture.
* Extendability.
* Object-oriented API.

@kaskar2008, whaddaya think?

**Comment by kaskar2008** [comment]
1. WebSQL is deprecated
2. **Keep data up-to-date**, **Ability to map data entities to request handlers**: working draft you can see [here](https://github.com/KazanExpress/web-orm/tree/prototype/src)
3. We need to deal with events. [js-simple-events](https://github.com/VeryWow/js-simple-events) is a perfect match
4. Declaration for **add/update/delete** methods.
5. Find/filter is a good addition

**Comment by Raiondesu** [comment]
Finalized.
